mod app;
mod constant;
mod coproduct;
pub(crate) mod empty;
mod identity;
mod lambda;
pub(crate) mod naturals;
mod pair;
pub(crate) mod terms;
pub(crate) mod types;
mod unit;
pub(crate) mod universe;
pub(crate) mod variable;
